# Generated by Django 3.2.4 on 2021-10-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='neighborhood',
            field=models.CharField(default='Faltando', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='complement',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
