# Generated by Django 3.2.4 on 2021-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_patient_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
