# Generated by Django 3.2.4 on 2021-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20211003_0355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("A Confirmar", "A Confirmar"),
                    ("Confirmado", "Confirmado"),
                    ("Finalizado", "Finalizado"),
                ],
                max_length=20,
            ),
        ),
    ]
